version: "2"

services:

  db:
    build:
      args:
        no_proxy: 127.0.0.1
        http_proxy:
        https_proxy:
    restart: "no"
    volumes:
      - /opt/docker/mattermost/volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    dns_search: .

  app:
    build:
      args:
        no_proxy: 127.0.0.1
        http_proxy:
        https_proxy:
        edition: team

    restart: "no"
    volumes:
      - /opt/docker/mattermost/volumes/app/mattermost/config:/mattermost/config:rw
      - /opt/docker/mattermost/volumes/app/mattermost/data:/mattermost/data:rw
      - /opt/docker/mattermost/volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    dns_search: .

  web:
    build:
      args:
        no_proxy: 127.0.0.1
        http_proxy:
        https_proxy:
    ports:
      - "443:443"
    restart: "no"
    volumes:
      # This directory must have cert files
      - /opt/docker/mattermost/volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    dns_search: .
    depends_on:
      - app
