- hosts: all
  remote_user: root
#  ask_pass: True
#  host_key_checking: False

  vars:
    service: mattermost.service

  tasks:
    - name: set mattermost systemd service
      template: src="{{ service }}.j2" dest="/etc/systemd/system/{{ service }}"

    - name: enable mattermost systemd service
      service: name="{{ service }}" enabled=yes state=started daemon_reload=yes

  handlers:
    - name: mattermost restart
      service: name=mattermost state=restarted
